export const REGISTER_STRINGS = {
  title: "Create Your Account",
  step1: "Basic Information",
  step2: "Business Details",
  step3: "Profile Setup",
  fullName: "Full Name",
  username: "Username",
  email: "Email Address",
  password: "Password",
  confirmPassword: "Confirm Password",
  businessId: "Business ID",
  outlet: "Outlet ID (Optional)",
  phone: "Phone Number",
  bio: "Bio",
  role: "Select Your Role",
  avatar: "Upload Profile Image",
  coverImage: "Upload Cover Image",
  next: "Next",
  back: "Back",
  submit: "Register",
  terms: "By registering, you agree to our Terms and Privacy Policy.",
};
